version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - POSTGRESQL_DATABASE=bitnami_airflow
    networks:
      - airflow-tier
    volumes:
      - postgresql_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - airflow-tier
    volumes:
      - redis_data:/bitnami

  airflow:
    image: bitnami/airflow:latest
    container_name: airflow
    ports:
      - "8060:8080"
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USER=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=ito.nhgautam@gmail.com
    networks:
      - airflow-tier

networks:
  airflow-tier:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
